version: "3.8"
services:
  backend:
    image: "kalilmvp/springboot-react-fullstack:1.5.2022.19.33.43"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
