version: "3.8"
services:
  backend:
    image: "kalilmvp/springboot-react-fullstack:2.5.2022.11.26.32"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
