version: "3.8"
services:
  backend:
    image: "kalilmvp/springboot-react-fullstack:5.5.2022.21.29.8"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
